config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "registrations",
    sessions: "sessions"
  }
  resources :profiles, controllers: {
    show: 'profile'
  }

  devise_scope :user do
    get "/get_in", to: "registrations#new", as: :sign_up
    get "/login", to: "sessions#new", as: :sign_in
    delete "/sign_out", to: "devise/sessions#destroy"
  end

  root 'articles#index'
  resources :articles do
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :comments

    has_rich_text :body
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :article
    belongs_to :user
end

app/models/profile.rb
class Profile < ApplicationRecord
    belongs_to :user

    validates :username, presence: true, uniqueness: true
    validates :first_name, presence: false
    validates :last_name, presence: false
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  attr_accessor :username

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile
  has_many :articles, dependent: :destroy
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < UsersController
  skip_before_action :authenticate_user!, only: %i[ index show ]
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all.reverse
  end

  # GET /articles/1 or /articles/1.json
  def show
    @comment = Comment.new
    @comment.article_id = @article.id
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :subheader, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @article = Article.find(params[:article_id])
        @comment = Comment.create(comment_params)
        @comment.article_id = @article.id
        if @comment.save
          redirect_to article_path(@article)
        end
    end


    private
    def comment_params
        params.require(:comment).permit(:user_id, :body)
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    def new
        super
    end

    def create
        super
        resource.save!
        Profile.create!(username: params[:user][:username], user_id: resource.id)
    end

    private
    def user_registration_params
        params.require(:user).permit(
            :email,
            :password,
            :password_confirmation
        )
    end

    def profile_registration_params
        params.require(:profile).permit(:username)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!

    layout 'application'

    def index
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def markdown(text)
        options = %i[
          hard_wrap autolink no_intra_emphasis tables fenced_code_blocks
          disable_indented_code_blocks strikethrough lax_spacing space_after_headers
          quote footnotes highlight underline
        ]
        Markdown.new(text, *options).to_html.html_safe
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/_comment.html.erb
<div class='comment-block'>
  <p><%= link_to comment.user.profile.username %> said <%= time_ago_in_words(comment.created_at) %> ago</p>
  <p class="comment-body"><%= comment.body %></p>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>:
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :subheader %>:
    <%= form.text_field :subheader %>
  </div>

  <div class="field">
    <%= form.label :body %>:<br>
    <%= form.rich_text_area :body, rows: 8 %>
  </div>

  <div class="actions">
    <%= form.submit "Post Article" %>
    <%= link_to 'Back', articles_path %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class='article-edit'>
    <h1>Editing Article</h1>

    <%= render 'form', article: @article %>

    <%= link_to 'Show', @article %>
</div>

app/views/articles/index.html.erb
<section class='article-feed'>
  <% @articles.each do |article| %>
    <div class='article-card'>
      <%# TODO: Link username to user profile %>
      <div class='article-card--user-section'>
        <div class='article-card--profile-icon'>
          <i class="far fa-user-circle"></i>
        </div>
        <div class='article-card--info'>
          <a href='/' class='article-card--user'><%= article.user.profile.username %></a>
          <br>
          <span class='date'><%= time_ago_in_words(article.created_at) %> ago</span>
        </div>
      </div>
      <h3><a href=<%= article_path(article.id) %> class='article-card--link' ><%= article.title %></a></h3>
    </div>
  <% end %>
</section>

app/views/articles/new.html.erb
<section class='article-create'>
    <h1>Compose Article</h1>

    <%= render 'form', article: @article %>
</section>

app/views/articles/show.html.erb
<div class='action-buttons'>
  <% if user_signed_in? && current_user.id == @article.user_id %>
    <%= link_to 'Edit', edit_article_path(@article), class: 'button' %>
  <% end %>
  <%= link_to 'Back', articles_path, class: 'button prev-btn' %>
</div>

<section class='article-show'>
  <div class='article-header'>
    <h1><%= @article.title %></h1>
    <h2><%= @article.subheader %></h2>
  </div>

  <div class='article-content'>
    <%= @article.body %>
  </div>
</section>

<section class='comment'>
  <h2>Comments</h2>
  <% if user_signed_in? %>
    <%= render partial: 'comments/form' %>
  <% else %>
    <%= link_to 'Sign in to comment', sign_in_path %>
  <% end %>
  <% if @article.comments.length > 0 %>
  <hr>
  <%= render partial: 'articles/comment', collection: @article.comments.reverse %>
  <% end %>
</section>

app/views/comments/_form.html.erb
<%= form_for [ @article, @comment ] do |f| %>
  <p>
    <%= f.label "#{@article.user.profile.username}" %>
    <%= f.hidden_field 'user_id', value: current_user.id %>
  </p>
  <p>
    <%= f.text_area :body, class: 'comment-area' %>
  </p>
  <p class='comment-submit'>
  <%= f.submit 'Submit', class: 'comment-btn' %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DuckLog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/common/header' %>

    <%= yield %>
  </body>
</html>

app/views/layouts/common/_header.html.erb
<section class='navigation'>
    <div class='topnav'>
        <div class='topnav--navheader'>
            <a href='/' class='site-logo'>DuckLog</a>
            <nav>
            <% if user_signed_in? %>
                <%= button_to "Create Article", new_article_path, method: :get, class: 'button site-article' %>
                <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'button site-logout' %>
            <% else %>
                <%= button_to "Login", sign_in_path, method: :get, class: 'button site-login' %>
                <%= button_to "Register", sign_up_path, method: :get, class: 'button site-register' %>
            <% end %>
            </nav>
        </div>
    </div>
</section>

app/views/users/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Subheader:</strong>
  <%= @article.subheader %>
</p>

<p>
  <strong>Body:</strong>
  <%= @article.body %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", sign_in_path %>
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %>
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%- if controller_name != 'registrations' %><br><% end %><%= link_to "Forgot your password?", new_password_path(resource_name) %>
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %>
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %>
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %>
  <% end %>
<% end %>